
project_id = "tmffcijysdajfwyoqvuh"

[functions.chat]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.chatlifeatlas]
verify_jwt = true

[functions.send-feedback]
verify_jwt = true

[build.environment]
NODE_VERSION = "18"
